### ISSUE TITLE
PhpStorm2019.1 has no plugin submenu which present in Overview

### ISSUE THREAD

**Issue by xenion54** [monosoul/git-extended-update-index-plugin#1]
![image](https://user-images.githubusercontent.com/51945081/59659374-bfd11b00-91ae-11e9-9953-be738b39387f.png)

**Comment by monosoul** [comment]
Hi @xenion54 ,

Thanks for reporting the issue. I've checked it with IntelliJ IDEA 2019.1.3 and it has the plugin submenu. It should work with any other product based on the IntelliJ platform, but maybe something is different with PhpStorm. I'll try to take a look into it this month.

**Comment by xenion54** [comment]
> Hi @xenion54 ,
> 
> Thanks for reporting the issue. I've checked it with IntelliJ IDEA 2019.1.3 and it has the plugin submenu. It should work with any other product based on the IntelliJ platform, but maybe something is different with PhpStorm. I'll try to take a look into it this month.

Thanks, man.

**Comment by monosoul** [comment]
> > Hi @xenion54 ,
> > Thanks for reporting the issue. I've checked it with IntelliJ IDEA 2019.1.3 and it has the plugin submenu. It should work with any other product based on the IntelliJ platform, but maybe something is different with PhpStorm. I'll try to take a look into it this month.
> 
> Thanks, man.

So, I took a look into it and it seems like for some reason as soon as I enable the php plugin in IntelliJ IDEA, I can't add any new items to IntelliJ's context menus. I tried different menus and different items, the result is always the same. And when the plugin is disabled - everything works like it should. So I guess there's some problem with the php plugin. Do you have any other plugins that add some new context menus? Also, did you have this problem with a previous version of PhpStorm?

**Comment by xenion54** [comment]
I disable all plugins exlcude "Git integration" and "git-extended-update-index-plugin". The result as previous, still has no "git-extended-update-index-plugin" menu items.
"BashSupport" plugin adding context items successfully. Unfortunately, i have no other versions of PhpStorm.

**Comment by monosoul** [comment]
Hey @xenion54 , sorry for the delay. I released a new version today, ideally it should fix your issue. It should appear in the JetBrains plugins repo within two days. In the meantime you can try installing it manually: https://github.com/monosoul/git-extended-update-index-plugin/releases/download/0.0.2/Git.extended.update-index-0.0.2.zip
