### ISSUE TITLE
Add an option to show all skip-worktree files.

### ISSUE THREAD

**Issue by YevhenK-MA** [monosoul/git-extended-update-index-plugin#4]
Poor man's version: add context menu option that will simply git ls-files -v . | grep ^S and show the output somwhere.
Perfect solution would be adding option to show skip-worktree files here:
![image](https://user-images.githubusercontent.com/62568852/93746583-0b6a4400-fbfe-11ea-95fb-ae29794deedf.png)

Can you do this, please? For now, I don't know how to check which files I skipped and how to un-skip them.

**Comment by monosoul** [comment]
Ah damn, I didn't get an email for this issue. Yep, that's a good idea, I'll have a look into that.

**Comment by monosoul** [comment]
@YevhenK-MA the new version of the plugin with the feature you requested just got published to Jetbrains Plugin Repo. Make sure to check it out 😉 

Also, if you like the plugin, please, consider leaving a review, it will help others notice it.

https://plugins.jetbrains.com/plugin/11217-git-extended-update-index/reviews

Thanks!
