### ISSUE TITLE
Keyboard shortcuts are not working

### ISSUE THREAD

**Issue by igorwo** [monosoul/git-extended-update-index-plugin#7]
I have assigned two shortcuts but they seems not to be working (used when the file is open)
![image](https://user-images.githubusercontent.com/83964305/127122621-a13f80a8-f514-4a40-b738-2c6e01a53753.png)

Tested on Android Studio 4.2.2 + git-extended-update-index-plugin 0.0.3

BTW Great Plugin! THX for creating it!

**Comment by monosoul** [comment]
Thanks for creating the report, I'll have a look into it

**Comment by monosoul** [comment]
@igorwo I just checked it, and for me shortcuts work. Could it be, that the shortcut you're trying to use is assigned to something else in your OS?  Could you try assigning a different shortcut?
