### ISSUE TITLE
Only the old `0.0.3` Version is available in IDE

### ISSUE THREAD

**Issue by igorwo** [monosoul/git-extended-update-index-plugin#8]
![image](https://user-images.githubusercontent.com/83964305/127123206-f2d2a0a2-5def-4517-8514-97db49ab3327.png)

We should see the newest one in the Marketplace.

**Comment by monosoul** [comment]
Hey @igorwo , which IntelliJ version do you use?

**Comment by monosoul** [comment]
I suppose you're using Android studio, here's the compatibility table for it:
![image](https://user-images.githubusercontent.com/5037832/127293542-ba8fc50f-a154-43e3-a4ba-79e82e5f72f7.png)

**Comment by monosoul** [comment]
Looks like you'd have to wait for Android Studio Bumblebee to release (it's based on IntelliJ 2021.1.1) to be able to use the latest version.
